routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('alteracao', 'ControllerAlteracao');
Route::resource('categoria', 'ControllerCategoria');
Route::resource('parametro', 'ControllerParametro');
Route::resource('atividade_preponderante', 'ControllerAtividadePreponderante');
Route::resource('amostra', 'ControllerAmostra');
Route::post('amostra/confirm', 'ControllerAmostra@confirm')->name('amostra.confirm');
Route::get('amostra/complete/{id}', 'ControllerAmostra@show_complete')->name('amostra.complete');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Categoria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    protected $table = 'categoria';

    protected $fiilable = [
        'descricao',
        'nota',
        'qualidade',
        'semaforo'
    ];

    public function CategoriaParametro()
    {
        return $this->belongsTo('App\Models\CategoriaParametro', 'fk_categoria', 'id');
    }
}

resources/views/categoria/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 py-5">
            <div class="card">
                <div class="card-header">{{ __('Dados da Categoria') }}</div>

                <div class="card-body">
                    @if(isset($objeto))
                        <form method="POST" action="{{ route('categoria.update', $objeto->id) }}">
                            {{ method_field('PATCH') }}
                    @else
                        <form method="POST" action="{{ route('categoria.store') }}">
                    @endif

                        @csrf

                        {{-- ERROS --}}
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                     <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        {{-- DESCRICAO --}}
                        <div class="form-group row">
                            <label for="descricao" class="col-md-4 col-form-label text-md-right">{{ __('Descrição') }}</label>

                            <div class="col-md-6">
                                <input id="descricao" type="text" class="form-control" name="descricao" value="@if(isset($objeto)){{ $objeto->descricao}}@endif" maxlength="80" required autofocus>

                                @if ($errors->has('descricao'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('descricao') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{-- NOTA --}}
                        <div class="form-group row">
                            <label for="nota" class="col-md-4 col-form-label text-md-right">{{ __('Nota') }}</label>

                            <div class="col-md-6">
                                <input id="nota" type="number" min="0" max="100" class="form-control" name="nota" value="@if(isset($objeto)){{$objeto->nota}}@endif" maxlength="11" required autofocus>

                                @if ($errors->has('nota'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('nota') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{-- QUALIDADE --}}
                        <div class="form-group row">
                            <label for="qualidade" class="col-md-4 col-form-label text-md-right">{{ __('Qualidade') }}</label>

                            <div class="col-md-6">
                                <input id="qualidade" type="text" class="form-control" name="qualidade" value="@if(isset($objeto)){{$objeto->qualidade}}@endif" maxlength="10" required autofocus>

                                @if ($errors->has('qualidade'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('qualidade') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        {{-- SEMAFORO --}}
                        <div class="form-group row">
                            <label for="semaforo" class="col-md-4 col-form-label text-md-right">{{ __('Semáforo') }}</label>

                            <div class="col-md-6">
                                <input id="semaforo" type="text" class="form-control" name="semaforo" value="@if(isset($objeto)){{$objeto->semaforo}}@endif" maxlength="10" required autofocus>

                                @if ($errors->has('semaforo'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('semaforo') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Salvar') }}
                                </button>

                                <a class="btn btn-danger" href="{{ route('categoria.index') }}">{{ __('Cancelar') }}</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/categoria/list.blade.php
@extends('layouts.app')

@section('content')
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
    @if (session('error'))
        <div class="alert alert-danger">
            {{ session('error') }}
        </div>
    @endif

    <h2>Categorias</h2>
    <p class="separator"></p>
    <div class="table-responsive">
        <table class="table table-striped table-bordered" id="dataTable" aria-describedby="users_table" role="grid">
            <thead>
    			<tr>
                    <th>Descricao</th>
                    <th>Nota</th>
                    <th>Qualidade</th>
                    <th>Semáforo</th>
                    <th>Opções</th>
                </tr>
    		</thead>
    		<tbody>
                @foreach ($objetos as $obj)
                    <tr role="row" class="odd">
                        <td>{{$obj->descricao}}</td>
        				<td>{{$obj->nota}}</td>
        				<td>{{$obj->qualidade}}</td>
        				<td>{{$obj->semaforo}}</td>
        				<td class="d-flex justify-content-center">

                            <form action="{{ route('categoria.edit', $obj->id) }}" method="GET" style="margin-right:10px;">
               					<button type="submit" class="btn btn-sm btn-primary">
               						<i class="glyphicon glyphicon-pencil"></i> Editar
               				    </button>
                            </form>

                            <form action="{{ route('categoria.destroy', $obj->id) }}" method="POST">
                                @csrf
                                {{ method_field('DELETE') }}
                                <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Deseja realmente Excluir?')">
                                    <i class="glyphicon glyphicon-trash"></i>Excluir
                                </button>
                            </form>

        				</td>
        			</tr>
                @endforeach

            </tbody>
    	</table>
    </div>
    {{-- {{ $models->links() }} --}}
    <br>
    <a class="btn btn-primary" href="{{ route('categoria.create') }}">{{ __('Nova Categoria') }}</a>

@endsection